title: Alan Armstrong
logo: ([https://github.com/AlanCArmstrong/AlanCArmstrong.github.io/blob/main/Professional%20Pic.jpg])
#description: text below image
show_downloads: true
remote_theme: jekyll-theme-yat
